### PR TITLE
Add GHCR login and tag

### PR DESCRIPTION
**Pull request by adamus1red**
Publish containers to the Github Container Repo at the same time as docker hub

### CODE REVIEW

**Review by qdm12 — APPROVED** [review]
Awesome :100: !

Do you mind documenting in the Readme please? You can just add there is a mirror to the Docker Hub image in a one-liner, that should do :+1:

**Comment by fredericrous** [comment]
just an honest question: why would you want to publish the image on 2 different spots? what advantage does it bring in your experience?

**Comment by qdm12** [comment]
@fredericrous I guess as a backup, if Docker Hub goes down (it does, although rarely); Also Docker Hub has rate limiting (not a problem personally), but it can be problematic if you update your images automatically and have multiple updates e.g. the same day.

**Comment by adamus1red** [comment]
@qdm12 that should be the README updated.

**Review by qdm12 — APPROVED** [review]

**Comment by qdm12** [comment]
Awesome, thanks it's merged!!

**Pull request merged**
